language: python

sudo: required

dist: trusty

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

virtualenv:
  system_site_packages: true

install:
  - sudo apt-add-repository ppa:libccd-debs -y
  - sudo apt-add-repository ppa:fcl-debs -y
  - sudo apt-add-repository ppa:dartsim -y
  - sudo apt-add-repository ppa:personalrobotics -y
  - sudo apt-get update -q
  - sudo apt-get install python-dartpy python3-dartpy -y
  
script:
  - find /usr -name dartpy.so
  - python --version
  - python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
  - cd tests
  - python -m unittest test_*
  - cd ..
